
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-rec
owner: ucsb-cs156
repo_name: proj-rec
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-CRAtoVite","number":57,"title":"Vite Migration","url":"https://github.com/ucsb-cs156/proj-rec/pull/57"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-toRR7","number":56,"title":"React Router v7 Bump","url":"https://github.com/ucsb-cs156/proj-rec/pull/56"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addFormatter","number":55,"title":"Adding a Backend Code Formatter","url":"https://github.com/ucsb-cs156/proj-rec/pull/55"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s25-16","number":50,"title":"Draft PR for S25-16's work","url":"https://github.com/ucsb-cs156/proj-rec/pull/50"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s25-15","number":49,"title":"Draft PR for S25-15's work","url":"https://github.com/ucsb-cs156/proj-rec/pull/49"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s25-14","number":48,"title":"Draft PR for S25-14's work","url":"https://github.com/ucsb-cs156/proj-rec/pull/48"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-update-setup-java-to-v4","number":12,"title":"Pc update setup java to v4","url":"https://github.com/ucsb-cs156/proj-rec/pull/12"}]
